name: pytest varys

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Checkout certificate generator
      uses: actions/checkout@v3
      with:
        repository: rabbitmq/tls-gen
        path: tls-gen
    - name: Generate certificates
      run: |
        ls
        cd tls-gen/basic
        make
        make verify
        make info
        cd -
        mv -v tls-gen/basic/result/ca_certificate.pem .rabbitmq/ca_certificate.pem
        mv -v tls-gen/basic/result/server_*_certificate.pem .rabbitmq/server_localhost_certificate.pem
        mv -v tls-gen/basic/result/server_*_key.pem .rabbitmq/server_localhost_key.pem
        chmod a+rwx .rabbitmq/*
    - name: Run RabbitMQ server
      run: |
        pwd
        # if I do this, the port still seems to be bound in later steps,
        # so perhaps it doesn't matter when we run it
        docker run -d -v ./.rabbitmq:/.rabbitmq -e RABBITMQ_CONFIG_FILE=/.rabbitmq/rabbitmq.conf -p 5671:5671 -p 5672:5672 rabbitmq
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov
    - name: Install Varys
      run: python3 -m pip install -e .
    - name: Test with pytest
      run: |
        # maybe we need to run RabbitMQ server in the same step as tests
        # docker run -d -v $(pwd)/.rabbitmq:/.rabbitmq -e RABBITMQ_CONFIG_FILE=/.rabbitmq/rabbitmq.conf -p 5671:5671 -p 5672:5672 rabbitmq
        # sometimes the scripts hang because the channels can't be closed,
        # so run under a short timeout
        timeout 60s pytest -o log_cli=true --log-cli-level=DEBUG -v --cov-report=term-missing --cov=varys
    - name: 'Upload Logfile'
      uses: actions/upload-artifact@v3
      with:
        name: varys-logfile-${{ matrix.python-version }}
        path: tests/test.log
        retention-days: 5
        if-no-files-found: error
      if: ${{ always() }}

